[pytest]
pythonpath = src
bdd_features_base_dir = features/
# doctest_plus = enabled  # TODO it fails because of multiple 'v1.py' files
addopts = --strict-markers --junit-xml=test-results.xml --cov=src --cov-report xml:coverage.xml --cov-report json
markers =
  flaky: Flaky tests
  integration: Integration tests

# These will get injected as `os.environ` values, overriding anything else
# since Pydantic Settings uses `os.environ` before `.env` files
env_override_existing_values = 1
env_files =
  .env.test
  .env.test.local
