line-length = 150
indent-width = 4
show-fixes = true
exclude = [".git", "typings", "conftest.py", "*.md"]

# Minimum Python version: 3.12
target-version = "py312"

[format]

# Like Black:
# use double quotes for strings.
quote-style = "double"

# indent with spaces, rather than tabs.
indent-style = "space"

# respect magic trailing commas.
skip-magic-trailing-comma = false

# automatically detect the appropriate line ending.
line-ending = "auto"


[lint]
select = [
    "D",   # Docstrings
    "E",   # pycodestyle
    "F",   # Pyflakes
    "I",   # isort
    "PL",  # PyLint
    "SIM", # flake8-simplify
    "TID", # flake8-tidy-imports
    "W",   # warning
]

# Additional rules
extend-select = ["C4", "SIM", "TCH"]

fixable = ["ALL"]
ignore = [
    "TD",  # TODO
    "D1",    # Missing docstring # XXX
    "D104",  # Missing docstring in public package, like empty __init__.py # XXX?
    "PLR2004", # Magic value used in comparison,
    "TID252", # "Prefer absolute imports over relative imports from parent modules"
]

[lint.pydocstyle]
convention = "numpy"

[lint.per-file-ignores]
"tests/*" = ["D"]
