name: "[C]ontinuous [I]ntegration"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  PYTHONPATH: src
  DOCKER_BUILDKIT: 1
  PYRIGHT_PYTHON_FORCE_VERSION: latest

permissions:
  contents: read

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    permissions:
      checks: write
      issues: write # to be able to comment on released issues
      contents: write # to be able to publish a GitHub release
      id-token: write # to be able to authenticate with cloud providers
      pull-requests: write # to be able to comment on released pull requests
      security-events: write
    steps:
      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/commons/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-python/.github/actions/setup@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-pip/.github/actions/install-upgrade@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-pipx/.github/actions/install@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-poetry/.github/actions/self_add_plugins@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-poetry/.github/actions/install@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-compliance/.github/actions/codeql_init_and_analyze@main
        with:
          language: python

      - name: pypyr lock
        # if: github.ref == 'refs/heads/main' # TODO? or XXX?
        run: pypyr lock freeze=True

      # prettier & dockerlint
      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-node/.github/actions/setup@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-npm/.github/actions/install@main

      - name: pypyr lint
        run: pypyr lint stats=True

      - name: pytest per-file
        run: bash scripts/pytest/ci.ba.sh

      - name: doctest
        run: bash scripts/doctest/run.ba.sh

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-testing/.github/actions/junit@main
        with:
          reporter: python-xunit
          files_pattern: reports/**/junit-test*.xml
          # list-tests: all # XXX

      # Re-run tests for coverage purposes
      - name: pytest
        run: pypyr ci lint=False

      - name: poetry build
        run: poetry build

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-common/.github/actions/artifact-upload@main
        name: dist.zip

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-python/.github/actions/semantic-release@main
        continue-on-error: true # XXX FIXME
        with:
          verbosity: 1
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: git restore
        run: git restore .

      # FIXME
      # TODO Move to `github-actions-testing`
      # - name: coverage-badge
      #   if: github.ref == 'refs/heads/main'
      #   # uses: we-cli/coverage-badge-action@v1.0.1  # TODO
      #   uses: we-cli/coverage-badge-action@main

  #
  verify__scripts:
    name: Verify w/ scripts/setup_ci.ba.sh
    needs: verify
    runs-on: ubuntu-latest
    steps:
      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-python/.github/actions/setup@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-node/.github/actions/setup@main

      - name: scripts/setup_ci.ba.sh
        run: bash scripts/setup_ci.ba.sh

      - name: pypyr ci
        run: pypyr ci

  #
  verify__matrix:
    needs: verify
    if: github.ref_name == 'main'
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        # Different OS
        OS:
          - ubuntu-latest
          - macos-latest
          - windows-latest

        # Past/Future versions
        python-version:
          - 3.14.x
          # - 3.15.x # TODO

        # Different architectures
        architecture:
          - x64
          # - arm64 # "The version '3.12.x' with architecture 'arm64' was not found for Ubuntu 22.04."

    runs-on: ${{ matrix.OS }}
    name: "Verify: python@${{ matrix.python-version }} @ ${{ matrix.OS }}@${{ matrix.architecture }}"
    steps:
      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-python/.github/actions/setup@main
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-pip/.github/actions/install-upgrade@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-pipx/.github/actions/install@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-poetry/.github/actions/self_add_plugins@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-poetry/.github/actions/install@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-node/.github/actions/setup@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-npm/.github/actions/install@main

      - name: pypyr test
        run: pypyr ci

  #
  codeQL_actions:
    needs: verify
    permissions:
      actions: read
      contents: read
      security-events: write

    # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
    uses: percebus/github-actions-compliance/.github/workflows/codeql_analyze.yml@main
    name: CodeQL analyze
    with:
      language: actions
    secrets:
      SSH_KEY_PRIVATE: ${{ secrets.SSH_KEY_PRIVATE }}

  #
  docker_build__matrix:
    needs: verify
    continue-on-error: true
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      max-parallel: 10
      matrix:
        include:
          # - base
          # - project
          # - dev
          - target: tested
            run: true
            scan-image: false

          # - base
          # - project
          - target: release
            run: ${{ github.ref_name == 'main' }}
            scan-image: ${{ github.ref_name == 'main' }}

    runs-on: ubuntu-latest
    name: docker build --target ${{ matrix.target }}
    steps:
      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        if: ${{ matrix.run }}
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}

      - name: scripts/prepare.ba.sh
        if: ${{ matrix.run }}
        run: bash scripts/prepare.ba.sh

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-docker/.github/actions/build@main
        if: ${{ matrix.run }}
        with:
          target: ${{ matrix.target }}
          scan-image: ${{ matrix.scan-image }}

  #
  # TODO? move this to github-actions-docker ?
  docker_compose:
    name: docker compose
    needs: docker_build__matrix
    runs-on: ubuntu-latest
    steps:
      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}

      - name: scripts/prepare.ba.sh
        run: bash scripts/prepare.ba.sh

      - name: docker compose up
        run: docker compose up --abort-on-container-exit
